name: Build Demucs-GUI Linux

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
        default: 'main'
      version:
        description: 'Version to build'
        required: true
        default: 'git-main'
      cpu:
        description: 'CPU only build'
        required: true
        default: false
        type: boolean
      cuda:
        description: 'CUDA build'
        required: true
        default: false
        type: boolean
      rocm:
        description: 'ROCm build'
        required: true
        default: false
        type: boolean
      optimize:
        description: 'Use symbolic link to save space cost by duplicating files'
        required: true
        default: false
        type: boolean
      compression:
        description: 'Compression method'
        required: true
        type: choice
        default: 'zstd'
        options:
          - 'zstd'
          - 'xz'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        build_type: [cpu, cuda, rocm]
        include:
          - build_type: cpu
            condition: ${{ github.event.inputs.cpu == 'true' }}
          - build_type: cuda
            condition: ${{ github.event.inputs.cuda == 'true' }}
          - build_type: rocm
            condition: ${{ github.event.inputs.rocm == 'true' }}
      fail-fast: false
    name: Build Demucs-GUI Linux ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check condition
        uses: action-pack/cancel@v1
        if: ${{ matrix.condition == false }}

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: 'build-repo'

      - name: Checkout Demucs GUI
        uses: actions/checkout@v4
        with:
          repository: 'CarlGao4/Demucs-Gui'
          ref: ${{ github.event.inputs.commit }}
          fetch-depth: 1
          submodules: 'recursive'
          path: 'Demucs-Gui'

      - uses: actions/setup-python@v5
        if: ${{ github.event.inputs.optimize == 'true' }}
        with:
          python-version: '3.11'

      - name: Download base image
        run: |
          curl -JLO https://github.com/CarlGao4/demucs-gui-linux-build/releases/download/env-base/Demucs-GUI-base.AppImage
          chmod +x Demucs-GUI-base.AppImage
          ./Demucs-GUI-base.AppImage --appimage-extract
          mv squashfs-root Demucs-GUI.AppDir

      - name: Install dependencies
        run: |
          ./Demucs-GUI.AppDir/opt/python3.11/bin/python3.11 -s -m pip install -r Demucs-Gui/requirements_${{ matrix.build_type }}.txt
          ./Demucs-GUI.AppDir/opt/python3.11/bin/python3.11 -s -m pip cache purge
          sudo apt-get update
          sudo apt-get install -y squashfs-tools appstream

      - name: Prepare data
        run: |
          cp -r Demucs-Gui/GUI/ ./Demucs-GUI.AppDir/GUI
          cd ./Demucs-GUI.AppDir/GUI
          find . -type f ! -name '*.py' | xargs rm -rf
          find . -type d -empty | xargs rm -rf
          cp -r ../../Demucs-Gui/fonts/ ./fonts
          cp -r ../../Demucs-Gui/icon/ ./icon
          mkdir pretrained
          cp ../../build-repo/htdemucs.yaml ./pretrained/htdemucs.yaml
          curl -JL https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th -o ./pretrained/955717e8-8726e21a.th
          sudo apt install appstream

      - name: Finalize
        run: |
          sed -i 's/RELEASE_VERSION/${{ github.event.inputs.version }}/' ./Demucs-GUI.AppDir/usr/share/metainfo/demucs-gui.appdata.xml
          sed -i "s/RELEASE_DATE/$(date -u +%Y-%m-%d)/" ./Demucs-GUI.AppDir/usr/share/metainfo/demucs-gui.appdata.xml
          appstreamcli validate ./Demucs-GUI.AppDir/usr/share/metainfo/demucs-gui.appdata.xml || true

      - name: Optimize size
        run: |
          find ./Demucs-GUI.AppDir -name '*.pyc' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '__pycache__' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.dist-info' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.egg-info' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.a' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.c' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.h' | xargs rm -rf
          find ./Demucs-GUI.AppDir -name '*.cpp' | xargs rm -rf
          find ./Demucs-GUI.AppDir -type d -empty | xargs rm -rf

      - name: Link duplicate files
        if: ${{ github.event.inputs.optimize == 'true' }}
        run: |
          python3 -m pip install tqdm
          python3 ./build-repo/ln_optimize.py ./Demucs-GUI.AppDir -y -j4

      - name: Create squashfs (ZSTD)
        if: ${{ github.event.inputs.compression == 'zstd' }}
        run: |
          mksquashfs ./Demucs-GUI.AppDir squash.squashfs -root-owned -noappend -comp zstd -mem 8G -b 1M -Xcompression-level 22
          curl -JLO https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64

      - name: Create squashfs (XZ)
        if: ${{ github.event.inputs.compression == 'xz' }}
        run: |
          mksquashfs ./Demucs-GUI.AppDir squash.squashfs -root-owned -noappend -comp xz -mem 8G -b 1M -Xdict-size 100%
          curl -JLO https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64

      - name: Pack Demucs GUI
        run: |
          rm -rf Demucs-GUI.AppDir
          cat runtime-x86_64 squash.squashfs > Demucs_GUI-x86_64-${{ github.event.inputs.version }}-${{ matrix.build_type }}.AppImage
          rm squash.squashfs
          chmod +x Demucs_GUI-x86_64-${{ github.event.inputs.version }}-${{ matrix.build_type }}.AppImage
          tar -cvf Demucs_GUI-x86_64-${{ github.event.inputs.version }}-${{ matrix.build_type }}.tar Demucs_GUI-x86_64-${{ github.event.inputs.version }}-${{ matrix.build_type }}.AppImage

      - name: Upload Demucs GUI
        uses: actions/upload-artifact@v4
        with:
          name: Demucs-GUI-${{ matrix.build_type }}
          path: ./Demucs_GUI-x86_64*.tar
